AWSTemplateFormatVersion: "2010-09-09"
Description: Application Container on ECS Cluster - AWS Fargate
Parameters:
  StackName:
    Type: String
    Default: teststack
    Description: Name of the Networking Stack which is already available
Resources:
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: assignmentapp
      Cpu: 512
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue: !Join [":", [!Ref "StackName", "ECSTaskExecutionRole"]]
      ContainerDefinitions:
        - Name: assignmentapp
          Image: DOCKER_REPO/assignmentapp
          Cpu: 512
          Memory: 1024
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp

  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName: assignmentapp
      TaskDefinition: !Ref Task
      Cluster:
        Fn::ImportValue: !Join [":", [!Ref "StackName", "ClusterName"]]
      LaunchType: FARGATE
      DesiredCount: 2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Fn::ImportValue: !Join [":", [!Ref "StackName", "SubnetOne"]]
            - Fn::ImportValue: !Join [":", [!Ref "StackName", "SubnetTwo"]]
          SecurityGroups:
            - Fn::ImportValue:
                !Join [":", [!Ref "StackName", "ContainerSecurityGroup"]]
      LoadBalancers:
        - ContainerName: assignmentapp
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: assignmentapp
      VpcId:
        Fn::ImportValue: !Join [":", [!Ref "StackName", "VPCId"]]
      Port: 8080
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /produce
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn:
        Fn::ImportValue: !Join [":", [!Ref "StackName", "PublicListener"]]
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - /*
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

Outputs:
  ProduceEventEndpoint:
    Description: Books API Endpoint
    Value: !Join ["", ["http://", !ImportValue DomainName, "/produce"]]
    Export:
      Name: "ProduceEventEndpoint"
